beam: 10 # 100 for alignment, 10 for training
retry_beam: 40 # 400 for alignment,  40 for training

features:
  type: "mfcc"
  use_energy: false
  frame_shift: 5

training:
  - monophone:
      num_iterations: 40
      max_gaussians: 1000
      subset: 20000
      boost_silence: 1.25

  - triphone:
      num_iterations: 35
      num_leaves: 2000
      max_gaussians: 10000
      cluster_threshold: -1
      subset: 10000
      boost_silence: 1.25
      power: 0.25

  - lda:
      num_leaves: 2500
      max_gaussians: 15000
      subset: 20000
      num_iterations: 35
      features:
          splice_left_context: 3
          splice_right_context: 3
